### ISSUE TITLE
Please issue a new version

### ISSUE THREAD

**Issue by schnoog** [HackerInside0/Arduino_SoftwareReset#10]
First: Thank you very much for this library.

When I tried to compile a sketch with it, it unfortunately failed.
Then I´ve seen https://github.com/qub1750ul/Arduino_SoftwareReset/issues/8
and changed the line in the file library.properties

Now it compiles just fine.

I have seen you've applied that change in the repository too, however, the official version 3.0.0 available in the Arduino library manager still has that faulty  setting.

Could you please issue a new version so that the updated code is available?

Thanks in advance

**Comment by qub1750ul** [comment]
Done
