### ISSUE TITLE
Error Adding

### ISSUE THREAD

**Issue by castro2487** [HackerInside0/Arduino_SoftwareReset#3]
Hi.

i was trying to add your library to my Arduino Uno and give me a error of PORT A was not declared.
![error](https://cloud.githubusercontent.com/assets/22665702/20348372/d8475a72-abe3-11e6-920e-640e111fadcc.png)

**Comment by qub1750ul** [comment]
Seems that you're using an old version of the library.
Updating the library to the latest version will surely fix the problem.
